---
title: "Minutes GIhub-MEF 29apr2020"
author: "Luisa M Mimmi"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    df_print: paged # default
    keep_md: no
    #theme: united
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# a custom R function to insert the correct syntax depending on the output format using the is_latex_output() and is_html_output() functions in knitr as follows:
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}

# `r colorize("some words in red", "red")`
```

### Meeting BILATERALE MEF - GI HUB 29 Aprile 2020
In attendance 
MLF Marie Lam-Frendo [marie.lam-frendo@gihub.org] // KAtarina Sirikow // Luisa Mimmi // Laura Palma // Gelsomina Vigliotti

- MLF: purpose of the meeting is the preparation for Strategic Council meeting. We sent a long deck, but there are a couple of priorities to discuss: 

1. the note on covid 19
2. the discussion about the business plan (especially relevant for Italy) 


- GV: Thanks. The document (GI Hub Concept Note: Post-COVID-19 response) was very interesting and it is a very relevant effort to figure out what will happen in the future. At this stage, we are reflecting on our priorities, trying to adapting them to the new environment - we are not ready yet to define all the priorities... still infrastructure investment will be at the core of recovery (like in post-2008). This could also be an opportunity to fasten some processes (digitalization, quality side, attention to environment). 
We know the challenges and we are learrning that health is a global public good. Crisis could come also from other global public goods... climate / technology (ciber attack) **how can investment strategies be adaptable to the new environment?**

You identified already in the paper the Italian presidency priorities: we cannot confirm they will stay as it is, but the priorities are not confirmed yet ( _maintenance_ will stay and is still relevant // focus on _environmental-based infrastructure_ exploit what we have ?// _inclusion_ will be very relevant, more than ever //we can't help looking at _health_ (action plan endorsed by Saudi Presidency) - any suggestion on how to operationalize it? // ??  _soft infra_  do we need to be concerned of our digital capacity? Can it suffer overload? 
- LP: Agree on continuity with Saudi presidency (digital.., ). I was surprised you are preparing this CN on COVID bc at the IWG meeting...  given there is the one OECD is preparing. Maybe you should have shared before last IWG and have a discussion with the troika. What you propose is very interesting

- MLF: we were willing to share if agreeable to the presidency and co-chair. Given the situation we will only talk to them end of this week... there were too much competing priorities. 
What we put in there in terms of next steps was vey tentative. We are reorienting the Business plan and are happy to include your priorities,  ... 

- MLF responding to GV: 
+ on _maintenance_ ... how do we approach this? For Finance Min and Central Banks it would be from a fiscal risk perspective and on this [IMF](https://www.imf.org/external/np/fad/publicinvestment/) is doing a good job with the contingent liability practice (they also have an analystical tool [PFRAM 2.0](https://www.imf.org/external/np/fad/publicinvestment/pdf/PFRAM2.pdf). That been said, this is a great tool, but there might be an element of collecting evidence.  It could be beneficial for practitioners to detail this more at the sectoral level and add case studies. 
There is a IMF paper beeing produced for the deputies finance meeting... haven't seen it. 
+ Another aspect is the _preventive and predictive maintenance_ ... (turn leakage into revenues). Switzerland is quite advanced in that, and there is some work that could be done. We would be happy to look into that.  (the angle is always:  how would this be relevant to the Finance Min and Central Banks? ) Of course this is something that would have initial cost in CAPEX then become OPEX and then also have better contingent liability risk management (you can size it better)
[LP: the IMF will produce the report on cont liab in the second half of the year] 

[GV: link? OECD progress on roadmap infra as an asset class]? 
MLF: it's a good summary, well presented, but it's a reminder of biggest impediments. risk mitigation ? key element is still rating...
[GV: What more could be done in this respect?] 
MLF: int the Bus Plan we try to tie up our work more to the G20 agenda (including infra as an asset class - underneath that you got many levers, fiscal space will be increasingly cons_trained)... one key element will be bring in more commercial banks //`r colorize("QUI NON CAPISCO", "red")` within the _regulatory capital requiremnet_, currently you got 12% capital requirement.  we a re proposing to bring in more commercial banks (we worked with moodys to know what exactly was the default rate out there. Moody shared a database anonimized that said 4%. Going from 12 to 4 is not envisaged, but 12%  to 10% will actually make a big difference. 10% or 9% would crowd in banks (Chief risk officers say it would be a huge change). 
--> going into next year we propose to work with [BIS](https://www.bis.org/) and also the banks 
2 elements at play:
1. _regulatory capital requiremnet_ 12% 
2. _default rate_ at 4% & _banks' risk weighted average_  (how they are building their own internal pricing) at 10% - influenced by the 12%.
I realize it is good to put some work out there (for example a big action of the is the debt reduction ...IFA working group) the tension is that's actually a tangible achievement of the G20

--> What are actual deliverables? 

GV: in fact talking with MDBs boards, you can have some assessments of risk while under the investment bank rating the risk is higher. (derisk the project earlier and then rate it... )
- MLF: good point, investors at the end if you don't have investment grade, no investment committee will.... what to do with investment grade? It has to do with rating agency. Moddys know... they don't want to become impediments... infra is a key enabler 
--> work together (there are examples of project rated 2 knocthes above the investment grade) with mododys, S&P to derisk and rate the projects ... innovative thinking that could be doable/ what G20 could do? Engage BIS or rating agencies formally? 

GV: the connection I see (regulatory constrainst to involve private sector) How realistic can this be? We could engage Central Banks
- MLF: I have been trying 
+ Mary Lamb : embedding someone in the PResidency? (like with the Saudi ?) helping you shape the agenda. It seems your topics remain more or less in line with our themes (except for maintenance)

LP: work on **data gap**? postponed to next year? my understanding is in the IWG it is not happening at this stage, but there will be some deliverables second half of the year. or next year? `r colorize("Infrastructure Data Initiative (IDI)", "red")`
- MLF: yes we were supposed to have an IDI workshop at IWG but there was no room because it was virtual 
We'll be asking presidency if we can organize one at the margin of the June meeting? 
We are working on connecting different datasets (economists and data scientists) --> **datalake** extracting what data? 

**financial performance of asset levels**, with moodys etc. Issues collaborating with IDI but this is our priority anyway 

+ on _environmental-based infrastructure_ 
- LM: circular economy as alternative initiative? 
- MLF: not stremlined into industry massively, we are very much at the beginning. (infratech adoption not very good in infrastructure, same thing with circular economy) 
Use of certain materials would entail re-rating. It's a matter of thought leadership . Although Infratech is more low-hanging  fruit (infrastructure funds that are attached to it) 
 this requires R&D money, which so far has not been put there. 
 
 Maybe in cities? The sub-sovereign level can be more prone to talk about that? 
 
+ on _inclusion_ // 
+ on _health_ // 
+ on _soft infra_ )
    



 


